small refactor
DionisiuV/second-assigment pull request #2
Opened 2022-11-29 12:09 UTC by DionisiuV

first commit

screens/data service done

nav service partially done, need to add back functionality

back functionality done

added alert dialog

alert dialog if back pressed from first fragment

refactor custom ui component

small refactor

wip

2022-11-29 12:33 UTC, LuteDroid requested changes
fix pending review Comments

2022-11-29 12:33 UTC, LuteDroid commented on app/src/main/java/com/valentin/secondhomework/application/KoinModules.kt
> +
empty module

2022-11-29 12:33 UTC, LuteDroid commented on app/src/main/java/com/valentin/secondhomework/model/service/dataService/DataService.kt
> +    fun getData(): MutableLiveData<List<RandomItem>>
More specific names - data is very general

2022-11-29 12:33 UTC, LuteDroid commented on app/src/main/java/com/valentin/secondhomework/model/service/dataService/DataServiceProvider.kt
> +        //if list is empty, get data from the api
// Comments should be used ONLY to highlight, notify, raise attention to other developers that something is tricky, requires special attention, or is just hard to understand (and cannot be simplified)
// You should NEVER commit code with todo's 
// You should never add logs to make your code more clear -> instead, you should clean the code

2022-11-29 12:33 UTC, LuteDroid commented on app/src/main/java/com/valentin/secondhomework/model/service/navService/MainActivityNavService.kt
> +    fun getNavController(): NavController
why do you need this? where do you need 'NavController' outside NavService?

2022-11-29 12:33 UTC, LuteDroid commented on app/src/main/java/com/valentin/secondhomework/model/service/navService/MainActivityNavServiceProvider.kt
> +        if (shouldSetupNav())
This is nice, but I don't think is necessary; also this might generate errors: can you point out a scenario where this will throw Exception, even if used properly?

2022-11-29 12:33 UTC, LuteDroid commented on app/src/main/java/com/valentin/secondhomework/view/activity/main/MainActivity.kt
> +    private fun handleBackBasedOnCurrentLocation(currentLocation: String) {
this is Business logic

2022-11-29 12:33 UTC, LuteDroid commented on app/src/main/java/com/valentin/secondhomework/view/activity/main/MainActivity.kt
> +        buildCloseAppAlertDialog().show()
this is business logic

2022-11-29 12:33 UTC, LuteDroid commented on app/src/main/java/com/valentin/secondhomework/view/activity/main/MainActivity.kt
> +        return viewModel.getNavController().currentDestination!!.label.toString()
oops!!

2022-11-29 12:33 UTC, LuteDroid commented on app/src/main/java/com/valentin/secondhomework/view/activity/main/MainViewModel.kt
> +class MainViewModel(
Naming could be a little better

2022-11-29 12:33 UTC, LuteDroid commented on app/src/main/java/com/valentin/secondhomework/view/screenOne/ScreenOneFragment.kt
> +        //if adapter not attached, make request to return mock data
oops!!

2022-11-29 12:33 UTC, LuteDroid commented on app/src/main/java/com/valentin/secondhomework/view/screenOne/ScreenOneFragment.kt
> +        customComponentRefreshListF.visibility = View.GONE
oops!!!

2022-11-29 12:33 UTC, LuteDroid commented on app/src/main/java/com/valentin/secondhomework/view/screenOne/ScreenOneFragment.kt
> +            findNavController().navigate(R.id.action_screenOneFragment_to_screenTwoFragment)
oops!!

2022-11-29 12:33 UTC, LuteDroid commented on app/src/main/java/com/valentin/secondhomework/view/screenOne/ScreenOneViewModel.kt
> +    fun getData(): LiveData<List<RandomItem>> {
oops!!

2022-11-29 12:33 UTC, LuteDroid commented on app/src/main/java/com/valentin/secondhomework/view/screenTwo/ScreenTwoFragment.kt
> +        //if adapter not attached, make request to return mock data
oops!!

2022-11-29 12:33 UTC, LuteDroid commented on app/src/main/java/com/valentin/secondhomework/view/screenTwo/ScreenTwoFragment.kt
> +        customComponentRefreshListF.visibility = View.VISIBLE
oops!!

2022-12-05 08:35 UTC, DionisiuV commented on app/src/main/java/com/valentin/secondhomework/view/activity/main/MainActivity.kt
> +    private fun handleBackBasedOnCurrentLocation(currentLocation: String) {
need to pass context if i want to move this into vm

2022-12-05 08:35 UTC, DionisiuV commented on app/src/main/java/com/valentin/secondhomework/view/activity/main/MainActivity.kt
> +        buildCloseAppAlertDialog().show()
need to pass context if i want to move this into vm

2022-12-05 12:39 UTC, merged